name: CI - Service Validation

on:
  push:
    branches: [ main, feature/ci-setup ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Razón del disparo manual'
        required: false
        default: 'Prueba manual de CI'  

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    # Variables globales para que Docker Compose las inyecte a los contenedores
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      STORAGE_ROOT_USER: ${{ secrets.STORAGE_ROOT_USER }}
      STORAGE_ROOT_PASSWORD: ${{ secrets.STORAGE_ROOT_PASSWORD }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      # Dentro de la red de Docker, usamos los nombres de los servicios
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db-relational:5432/${{ secrets.POSTGRES_DB }}
      MONGO_URL: mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongodb:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create dummy env files
        run: |
            touch .env
            mkdir -p bff-node && touch bff-node/.env

      - name: Set up Infrastructure (Docker Compose)
        run: |
          
          docker compose up -d
          
          
          sleep 40         
          
          docker ps

      - name: Run Linter (Inside Docker)
        run: |          
          docker compose exec -T document-processor flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Integration Tests (Inside Docker)
        env:          
          DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db-relational:5432/${{ secrets.POSTGRES_DB }}
          MONGO_URL: mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongodb:27017
          STORAGE_ENDPOINT: http://minio:9000
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ENV: test
        run: |          
          docker compose exec -T document-processor pytest -v