name: CI - Service Validation

on:
  push:
    branches: [ main, feature/ci-setup ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    # Estas variables las usa Docker Compose para levantar los contenedores
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      STORAGE_ROOT_USER: ${{ secrets.STORAGE_ROOT_USER }}      
      STORAGE_ROOT_PASSWORD: ${{ secrets.STORAGE_ROOT_PASSWORD }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db-relational:5432/${{ secrets.POSTGRES_DB }}
      MONGO_URL: mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongodb:27017


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create dummy env files
        run: |
            touch .env
            mkdir -p bff-node && touch bff-node/.env

      - name: Set up Infrastructure (Docker Compose)
        run: |
          # Levantamos pero sin que el healthcheck detenga el pipeline inmediatamente
          docker compose up -d || true
          
          echo "Esperando 30 segundos para capturar logs de error..."
          sleep 30
          
          # ESTO ES LO MÁS IMPORTANTE: Ver por qué falló la app
          echo "--- LOGS DE DOCUMENT PROCESSOR ---"
          docker logs doc_processor_app
          
          echo "--- ESTADO DE CONTENEDORES ---"
          docker ps -a
          
          # Si el contenedor está muerto, este comando hará que el paso falle 
          # pero ya habremos visto los logs arriba.
          docker compose ps | grep "doc_processor_app" | grep "Up"

      - name: Run Integration Tests (Inside Container)
        env:
          # SOBREESCRIBIMOS las variables para el entorno de TEST dentro del contenedor
          ENV: test
          DB_HOST: db-relational
          DB_PORT: 5432
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          # Construimos la URL completa como la espera tu App
          DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db-relational:5432/${{ secrets.POSTGRES_DB }}
          
          MONGO_HOST: mongodb
          MONGO_PORT: 27017
          MONGO_DB_NAME: audit_db
          MONGO_URL: mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongodb:27017/audit_db?authSource=admin
          
          # CAMBIO CLAVE: Aquí usamos 'minio' porque estamos DENTRO de la red de Docker          
          STORAGE_HOST: http://minio:9000
          STORAGE_PORT:  ${{ secrets.STORAGE_PORT }}
          STORAGE_BUCKET_NAME: documents
          
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        run: |
          # Ejecutamos el linter y los tests en una sola ráfaga dentro del contenedor
          docker compose exec -T document-processor flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          docker compose exec -T document-processor pytest -v