name: Docker Publish compliance-processor

on:
  push:
    branches: [ "main" ]
    paths:
      - 'bff-node/**'
      - 'frontend-react/**'
      - 'service-doc-proc/**'
  
  workflow_dispatch:
    inputs:
      service:
        description: 'Selecciona el servicio a construir'
        required: true
        default: 'service-doc-proc'
        type: choice
        options:
          - bff-node
          - frontend-react
          - service-doc-proc
      tag_name:
        description: 'Etiqueta personalizada'
        required: false
        default: 'manual-build'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Metadata
      id: meta-calc
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          # Caso Manual
          CONTEXT="${{ github.event.inputs.service }}"
          TAG="${{ github.event.inputs.tag_name }}"
        else
          # Caso Push (Ejemplo simplificado: detectamos el primer cambio relevante)
          # En producción se suele usar una matriz, pero aquí cumplimos tu orden de 'decirle qué crear'
          CONTEXT="service-doc-proc"
          TAG="latest"
        fi

        # Mapeo lógico de nombres de imagen
        case "$CONTEXT" in
          "bff-node") IMAGE="compliance-bff" ;;
          "frontend-react") IMAGE="compliance-frontend" ;;
          "service-doc-proc") IMAGE="compliance-processor" ;;
        esac

        # Exportación profesional vía outputs
        echo "service_context=$CONTEXT" >> $GITHUB_OUTPUT
        echo "image_name=$IMAGE" >> $GITHUB_OUTPUT
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        # Acceso seguro mediante el contexto de pasos
        context: ./${{ steps.meta-calc.outputs.service_context }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.meta-calc.outputs.image_name }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.meta-calc.outputs.image_name }}:${{ steps.meta-calc.outputs.image_tag }}